homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret house_latitude
  longitude: !secret house_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret house_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Toronto

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret ha_api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

####################################
#
#
#           Sensors
#   
#
####################################

sensor:

    #Weather Prodiction
  - platform: yr

  - platform: google_travel_time
    api_key: !secret google_travel_api_key_mike
    origin: !secret google_travel_origin_house
    destination: !secret google_travel_destination_mike_work
    name: Mikes Drive to work

  - platform: google_travel_time
    api_key: !secret google_travel_api_key_alicia
    origin: !secret google_travel_origin_house
    destination: !secret google_travel_destination_alicia_work
    name: Alicia's Drive to work

  - platform: worldclock
    time_zone: America/Toronto

 

# Text to speech
tts:
  platform: google

#####################################
#
#
#           Sensors
#   
#
####################################

group:
    bedroom_lights:
        - group.bed_accent_lights
        - group.bed_lights
    bed_lights:
        - light.alicias_light
        - light.mikes_light
    bed_accent_lights:
        - switch.closet_light
        - switch.dresser_light


###################################
#
#
#           Devices
#   
#
####################################


wink:
  access_token: !secret wink_access_token 

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

####################################
#
#
#           Controllers
#   
#
####################################

# Amazon Echo example configuration.yaml entry
emulated_hue:

#media_player:
#  - platform: vlc

####################################
#
#
#           Scene's
#   
#
####################################


scene:
    - name: Bedroom Normal
      entities:
          group.bed_lights:
              state: on
              brightness: 250
          group.bed_accent_lights:
              state: on
    - name: Bedroom Movie
      entities:
          group.bed_lights:
              state: on
              brightness: 60
          group.bed_accent_lights:
              state: off
    - name: Bedroom Off
      entities:
          group.bed_lights
              state: off
          group.bed_accent_lights:
              state: off

